name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: graalvm@
    - name: Run tests
      run: sbt test
